In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
x = np.arange(10).reshape(-1, 1)
y = (2*x + 1).reshape(-1, 1)

In [7]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

## 모델의 선언, fit(학습), predict(예측)

In [9]:
# 모델 선언
model = LinearRegression()

In [10]:
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
# 학습
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# 예측
prediction = model.predict([[10.0]])

In [13]:
prediction

array([[21.]])